# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(default='', max_length=255, verbose_name='Текст 1')),
                ('text_2', models.CharField(default='', max_length=255, verbose_name='Текст 2')),
                ('text_3', models.CharField(default='', max_length=255, verbose_name='Текст 3')),
                ('text_4', models.CharField(default='', max_length=255, verbose_name='Текст 4')),
                ('text_5', models.CharField(default='', max_length=255, verbose_name='Текст 5')),
            ],
        ),
    ]
