# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170916_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заглавие')),
                ('under_title', models.CharField(default='', max_length=255, verbose_name='Текст под заглавием')),
                ('fact_1_title', models.CharField(default='', max_length=255, verbose_name='Название факта 1')),
                ('fact_1_value', models.IntegerField(default=0, verbose_name='Значение факта 1')),
                ('fact_1_icon', models.CharField(default='', max_length=255, verbose_name='Иконка факта 1')),
                ('fact_2_title', models.CharField(default='', max_length=255, verbose_name='Название факта 2')),
                ('fact_2_value', models.IntegerField(default=0, verbose_name='Значение факта 2')),
                ('fact_2_icon', models.CharField(default='', max_length=255, verbose_name='Иконка факта 2')),
                ('fact_3_title', models.CharField(default='', max_length=255, verbose_name='Название факта 3')),
                ('fact_3_value', models.IntegerField(default=0, verbose_name='Значение факта 3')),
                ('fact_3_icon', models.CharField(default='', max_length=255, verbose_name='Иконка факта 3')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_1',
            field=models.ImageField(upload_to='uploads/', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_2',
            field=models.ImageField(upload_to='uploads/', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_3',
            field=models.ImageField(upload_to='uploads/', verbose_name='Изображение 3'),
        ),
    ]
