# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170917_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заглавие')),
                ('under_title', models.CharField(default='', max_length=255, verbose_name='Текст под заглавием')),
                ('reason_1_title', models.CharField(default='', max_length=255, verbose_name='Название причины 1')),
                ('reason_1_text', models.CharField(default='', max_length=255, verbose_name='Текст причины 1')),
                ('reason_1_icon', models.CharField(default='', max_length=255, verbose_name='Иконка причины 1')),
                ('reason_2_title', models.CharField(default='', max_length=255, verbose_name='Название причины 2')),
                ('reason_2_text', models.CharField(default='', max_length=255, verbose_name='Текст причины 2')),
                ('reason_2_icon', models.CharField(default='', max_length=255, verbose_name='Иконка причины 2')),
                ('reason_3_title', models.CharField(default='', max_length=255, verbose_name='Название причины 3')),
                ('reason_3_text', models.CharField(default='', max_length=255, verbose_name='Текст причины 3')),
                ('reason_3_icon', models.CharField(default='', max_length=255, verbose_name='Иконка причины 3')),
                ('reason_4_title', models.CharField(default='', max_length=255, verbose_name='Название причины 4')),
                ('reason_4_text', models.CharField(default='', max_length=255, verbose_name='Текст причины 4')),
                ('reason_4_icon', models.CharField(default='', max_length=255, verbose_name='Иконка причины 4')),
                ('reason_5_title', models.CharField(default='', max_length=255, verbose_name='Название причины 5')),
                ('reason_5_text', models.CharField(default='', max_length=255, verbose_name='Текст причины 5')),
                ('reason_5_icon', models.CharField(default='', max_length=255, verbose_name='Иконка причины 5')),
                ('reason_6_title', models.CharField(default='', max_length=255, verbose_name='Название причины 6')),
                ('reason_6_text', models.CharField(default='', max_length=255, verbose_name='Текст причины 6')),
                ('reason_6_icon', models.CharField(default='', max_length=255, verbose_name='Иконка причины 6')),
                ('under_text', models.TextField(default='', max_length=255, verbose_name='Текст внизу секции')),
            ],
            options={
                'verbose_name': 'Секция WhyUs',
                'verbose_name_plural': 'Секция WhyUs',
            },
        ),
        migrations.AlterModelOptions(
            name='factssection',
            options={'verbose_name': 'Секция Facts', 'verbose_name_plural': 'Секция Facts'},
        ),
    ]
