# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_skillssection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillssection',
            name='skill_1_value',
            field=models.IntegerField(default=0, verbose_name='Значение принципа 1'),
        ),
        migrations.AlterField(
            model_name='skillssection',
            name='skill_2_value',
            field=models.IntegerField(default=0, verbose_name='Значение принципа 2'),
        ),
        migrations.AlterField(
            model_name='skillssection',
            name='skill_3_value',
            field=models.IntegerField(default=0, verbose_name='Значение принципа 3'),
        ),
    ]
