# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_servicessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Секция Quote',
                'verbose_name_plural': 'Секция Quote',
            },
        ),
    ]
