# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_quotesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заглавие')),
                ('under_title', models.CharField(default='', max_length=255, verbose_name='Текст под заглавием')),
                ('text', models.TextField(default='', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Секция Pricing',
                'verbose_name_plural': 'Секция Pricing',
            },
        ),
    ]
