# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pricingsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSchemeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заглавие')),
                ('under_title', models.CharField(default='', max_length=255, verbose_name='Текст под заглавием')),
                ('item_1_title', models.CharField(default='', max_length=255, verbose_name='Название пункта 1')),
                ('item_1_text', models.TextField(default='', verbose_name='Текст пункта 1')),
                ('item_1_image', models.ImageField(upload_to='uploads/', verbose_name='Изображение пункта 1')),
                ('item_2_title', models.CharField(default='', max_length=255, verbose_name='Название пункта 2')),
                ('item_2_text', models.TextField(default='', verbose_name='Текст пункта 2')),
                ('item_2_image', models.ImageField(upload_to='uploads/', verbose_name='Изображение пункта 1')),
                ('item_3_title', models.CharField(default='', max_length=255, verbose_name='Название пункта 3')),
                ('item_3_text', models.TextField(default='', verbose_name='Текст пункта 3')),
                ('item_3_image', models.ImageField(upload_to='uploads/', verbose_name='Изображение пункта 3')),
                ('item_4_title', models.CharField(default='', max_length=255, verbose_name='Название пункта 3')),
                ('item_4_text', models.TextField(default='', verbose_name='Текст пункта 3')),
                ('item_4_image', models.ImageField(upload_to='uploads/', verbose_name='Изображение пункта 3')),
                ('item_5_title', models.CharField(default='', max_length=255, verbose_name='Название пункта 3')),
                ('item_5_text', models.TextField(default='', verbose_name='Текст пункта 3')),
                ('item_5_image', models.ImageField(upload_to='uploads/', verbose_name='Изображение пункта 3')),
                ('under_text', models.TextField(default='', max_length=255, verbose_name='Текст внизу секции')),
            ],
            options={
                'verbose_name': 'Секция JobScheme',
                'verbose_name_plural': 'Секция JobScheme',
            },
        ),
    ]
