# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_jobschemesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_1_name', models.TextField(default='', verbose_name='Имя клиента 1')),
                ('item_1_position', models.TextField(default='', verbose_name='Должность клиента 1')),
                ('item_1_image', models.ImageField(upload_to='uploads/', verbose_name='Изображение клиента 1')),
                ('item_1_text', models.TextField(default='', verbose_name='Текст отзыва 1')),
                ('item_2_name', models.TextField(default='', verbose_name='Имя клиента 2')),
                ('item_2_position', models.TextField(default='', verbose_name='Должность клиента 2')),
                ('item_2_image', models.ImageField(upload_to='uploads/', verbose_name='Изображение клиента 2')),
                ('item_2_text', models.TextField(default='', verbose_name='Текст отзыва 2')),
                ('item_3_name', models.TextField(default='', verbose_name='Имя клиента 3')),
                ('item_3_position', models.TextField(default='', verbose_name='Должность клиента 3')),
                ('item_3_image', models.ImageField(upload_to='uploads/', verbose_name='Изображение клиента 3')),
                ('item_3_text', models.TextField(default='', verbose_name='Текст отзыва 3')),
            ],
            options={
                'verbose_name': 'Секция Testimonials',
                'verbose_name_plural': 'Секция Testimonials',
            },
        ),
    ]
