# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170918_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones_text', models.TextField(default='', verbose_name='Текст блока телефонов')),
                ('address_text', models.TextField(default='', verbose_name='Текст блока адреса')),
            ],
            options={
                'verbose_name': 'Секция Contacts',
                'verbose_name_plural': 'Секция Contacts',
            },
        ),
    ]
