# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contactssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderContactsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(default='', max_length=255, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(default='', max_length=255, verbose_name='Телефон 2')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Секция HeaderContacts',
                'verbose_name_plural': 'Секция HeaderContacts',
            },
        ),
    ]
