# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170919_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessection',
            name='service_4_icon',
            field=models.CharField(default='', max_length=255, verbose_name='Иконка услуги 4'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='service_4_text',
            field=models.CharField(default='', max_length=255, verbose_name='Описание услуги 4'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='service_4_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название услуги 4'),
        ),
    ]
