# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170922_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderContactsSection',
        ),
    ]
